/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 백엔드 생존 확인 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 부분 학교명 검색 */
        get: operations["searchSchools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{schoolCode}/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 날짜 범위의 중식 조회 */
        get: operations["getSchoolMeals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        SchoolSearchResponse: {
            items: components["schemas"]["SchoolSummary"][];
            total: number;
        };
        SchoolSummary: {
            schoolCode: string;
            educationOfficeCode: string;
            schoolName: string;
            educationOfficeName: string;
            locationName: string | null;
            schoolType: string | null;
        };
        MealRangeResponse: {
            school: components["schemas"]["SelectedSchool"];
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            meals: components["schemas"]["Meal"][];
        };
        SelectedSchool: {
            schoolCode: string;
            educationOfficeCode: string;
            schoolName: string;
            educationOfficeName: string;
        };
        Meal: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            mealType: "lunch";
            dishes: string[];
            origins: string[];
            nutrition: string[];
            calories: string | null;
            servingCount: number | null;
        };
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance?: string;
            /** @enum {string} */
            code: "INVALID_REQUEST" | "INVALID_DATE_RANGE" | "SCHOOL_NOT_FOUND" | "RATE_LIMITED" | "UPSTREAM_ERROR" | "UPSTREAM_UNAVAILABLE" | "INTERNAL_ERROR";
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 백엔드가 정상 동작 중임 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    searchSchools: {
        parameters: {
            query: {
                /**
                 * @description 검색할 학교명의 일부. 앞뒤 공백을 제거한 후 2자 이상이어야 한다.
                 * @example 서울고
                 */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 목록. 결과가 없으면 빈 배열을 반환한다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "schoolCode": "7010113",
                     *           "educationOfficeCode": "B10",
                     *           "schoolName": "서울고등학교",
                     *           "educationOfficeName": "서울특별시교육청",
                     *           "locationName": "서울특별시",
                     *           "schoolType": "고등학교"
                     *         }
                     *       ],
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["SchoolSearchResponse"];
                };
            };
            /** @description 검색어가 누락되었거나 2자 미만인 경우 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://example.invalid/problems/invalid-request",
                     *       "title": "Invalid request",
                     *       "status": 400,
                     *       "detail": "검색어는 공백을 제거한 후 2자 이상이어야 합니다.",
                     *       "instance": "/api/v1/schools",
                     *       "code": "INVALID_REQUEST",
                     *       "errors": {
                     *         "name": [
                     *           "검색어는 2자 이상 입력해 주세요."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 요청이 제한된 경우 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description NEIS가 처리 불가능한 오류를 반환한 경우 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description NEIS 연결 실패 또는 타임아웃 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getSchoolMeals: {
        parameters: {
            query: {
                /**
                 * @description 시도교육청 코드
                 * @example B10
                 */
                officeCode: string;
                /**
                 * @description 한국 표준시 기준 직전 달 1일 이상, 오늘 이하
                 * @example 2026-08-10
                 */
                from: string;
                /**
                 * @description from 이상이며 한국 표준시 기준 오늘 이하
                 * @example 2026-08-17
                 */
                to: string;
            };
            header?: never;
            path: {
                /**
                 * @description NEIS 행정표준코드
                 * @example 7010113
                 */
                schoolCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 기간 중 급식이 존재하는 날짜의 중식 목록. 날짜 오름차순이며 급식이 없는 날짜는 포함하지 않는다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "school": {
                     *         "schoolCode": "7010113",
                     *         "educationOfficeCode": "B10",
                     *         "schoolName": "서울고등학교",
                     *         "educationOfficeName": "서울특별시교육청"
                     *       },
                     *       "from": "2026-08-10",
                     *       "to": "2026-08-17",
                     *       "meals": [
                     *         {
                     *           "date": "2026-08-17",
                     *           "mealType": "lunch",
                     *           "dishes": [
                     *             "현미밥",
                     *             "미역국",
                     *             "닭갈비"
                     *           ],
                     *           "origins": [
                     *             "쌀: 국내산",
                     *             "닭고기: 국내산"
                     *           ],
                     *           "nutrition": [
                     *             "탄수화물(g): 92.1",
                     *             "단백질(g): 31.4"
                     *           ],
                     *           "calories": "742.3 Kcal",
                     *           "servingCount": 530
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["MealRangeResponse"];
                };
            };
            /** @description 필수 파라미터 누락, 잘못된 날짜 형식, 또는 역순이거나 직전 달 1일~오늘 범위를 벗어난 날짜 범위 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 조회 대상 학교를 확인할 수 없는 경우 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://example.invalid/problems/school-not-found",
                     *       "title": "School not found",
                     *       "status": 404,
                     *       "detail": "요청한 학교를 확인할 수 없습니다.",
                     *       "instance": "/api/v1/schools/7010113/meals",
                     *       "code": "SCHOOL_NOT_FOUND"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 요청이 제한된 경우 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description NEIS가 처리 불가능한 오류를 반환한 경우 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description NEIS 연결 실패 또는 타임아웃 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
